server:
  port: 8082
  servlet:
    context-path: /node2

#logging:
#  level:
#    org:
#      apache:
#        http: TRACE
#      elasticsearch:
#        client: DEBUG

# 不开启的话，排序不生效
knife4j:
  enable: true
  #  production: false
  basic:
    enable: false
    username: dewen
    password: dewen
  setting:
    # 禁用默认的Footer显示，如果要自定义的话该属性必须设置为false,否则不会生效
    enableFooter: false
    # 该属性为Boolean值,默认false，如果开发者要自定义Footer内容,该选项设置为true
    enableFooterCustom: true
    # 最终在Ui界面底部显示的Footer内容，支持Markdown格式
    footerCustomContent: Apache License 2.0 | Copyright  2022-[Dewen's Project](https://github.com/dewen2018)
    # enableOpenApi: false

spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/dewen_anything?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      filters:
        commons-log.connection-logger-name: stat,wall,log4j
      max-active: 16
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # validation-query: select 'x'
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 2
    timeout: 3000ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

jetcache:
  #统计间隔
  statIntervalMinutes: 1
  areaInCacheName: false
  local:
    #默认area
    default:
      type: caffeine
      keyConvertor: fastjson2
  remote:
    default:
      #使用lettuce
      type: redis.lettuce
      keyConvertor: fastjson2
      broadcastChannel: dewen-projectA
#      valueEncoder: java
#      valueDecoder: java
      poolConfig:
        minIdle: 1
        maxIdle: 50
        maxTotal: 1000
        maxWait: 1000
      uri: redis://127.0.0.1:6379/1
#      使用sentinel做自动主备切换
#      uri: redis-sentinel://127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381/?sentinelMasterId=mymaster
#      readFrom: slavePreferred
#      集群
#      mode: cluster
#      uri: ['redis://password@192.168.0.1:6379/0','redis://password@192.168.0.2:6379/0','redis://password@192.168.0.3:6379/0']
#      uri:
#        - redis://password@192.168.0.1:6379/0  #redis://密码@IP:端口/库
#        - redis://password@192.168.0.2:6379/0
#        - redis://password@192.168.0.3:6379/0
#      readFrom: masterPreferred #master优先
