server:
  port: 8080
spring:
  # ���ݿ��������
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ������Ϻ�׺������ֹmysql����,serverTimezone=GMT%2b8����ʱ��
    url: ENC(ul0PHqbRRNne1AUFzT4lPECv0JJ4tQVyoCo3e/+Va5kIAmsfdi5C2qXabhxOmvCW6YtvQoDhHVPbOgbu6anT1uU0+7NyeLqal5SLEVo0ptIT/CxIhKrSJShGJF+tuED+1zmovSm4WEdzmuiTy9egthTUSgudM9fKihNDH5RceIsmy2oulGpM7w==)
    username: ENC(yS81qZ65y8Cq/8z/JzuUnw==)
    password: ENC(kzoFuZEcOG90EfK2Fp+oSQ==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # ���ص�api�ӿڵ����ã�ȫ����Ч
  jackson:
    # ���ĳһ���ֶ�Ϊnull���Ͳ��ٷ�������ֶ�
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
# jasypt���ܵ��ܳ�
jasypt:
  encryptor:
    password: Y6M9fAJQdU7jNp5MW